FROM openjdk:8-jdk-alpine
LABEL maintainer "mikolajkomisarek@outlook.com"
WORKDIR /app
COPY projects /app
ENV JAVA_OPTS=""
# CMD ["cd /app"]
# CMD ["./gradlew -Dsonar.host.url=http://sonarqube:9000 sonarqube"]
# CMD ["sh", "-c", "tail -f /dev/null"]